# backend/facup_seedings_map.py
# Simple lookup: seed number → team display name.
# Keeps facup_scores.py clean and in sync with the frontend seedings file.

SEED_TEAM_MAP: dict[int, str] = {
    1:  "Klopp's Resurgence",
    2:  "Cheeks FC",
    3:  "Cincy Til I Cry",
    4:  "FC Wincinnati",
    5:  "Noni to be upset",
    6:  "Shege FC",
    7:  "Slopeds FC",
    8:  "wizards",
    9:  "Bend It Like Declan",
    10: "Beans and Rice",
    11: "Too Slot To Handle",
    12: "ReecesPieces",
    13: "Defense and DarkArts",
    14: "I miss jamie vardy",
    15: "Siuuuuu Later",
    16: "2026 Champions",
    17: "Carter's Angels",
    18: "Artetanyahu",
    19: "Cech Mate",
    20: "FirstPlaceBelow",
    21: "Peaky Reijnders",
    22: "Liberties&Lotteries",
    23: "Peps Lads",
    24: "somethimg",
    25: "lamine yamal party",
    26: "Rolls Rice",
    27: "Eze Dub",
    28: "The Tigers",
    29: "Boogie Woogie",
    30: "halaand is washed",
    31: "Aches and Pains",
    32: "Fred's Red Army",
    33: "Bamford's Baddies",
    34: "livin saliba loca",
    35: "hands",
    36: "ur dads fav team",
    37: "Mandem FC",
    38: "Cheeks Fc",
    39: "Soccer Team",
    40: "Red_Devils",
}
